spring.application.name=wigilabs

spring.datasource.url=jdbc:postgresql://localhost:5432/wigilabsdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=yJx2w3FvK9QeL8l6mZ5Tt9OqJb5A3xN0K+5Fs9Ys6aA=

springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
